import sqlite3
from contextlib import contextmanager
from config import DB_PATH

SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    google_id TEXT UNIQUE,
    email TEXT UNIQUE,
    name TEXT,
    picture TEXT,
    
    x_id TEXT UNIQUE,
    
    wallet_address TEXT UNIQUE,      -- same EVM address works on Hyperliquid too
    agent_address TEXT,                    -- delegated Hyperliquid signer, generated by us
    agent_key_encrypted BLOB,              -- Fernet-encrypted private key for agent_address
    api_key_hash TEXT,                     -- hash of the secret the agent must present to trade
    permissions_confirmed INTEGER DEFAULT 0,  -- set true once approve_agent is confirmed
    last_seen TEXT,                        -- updated on every successful agent call — powers "connected" status
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS trades (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    coin TEXT NOT NULL,
    is_buy INTEGER NOT NULL,
    size REAL NOT NULL,
    result TEXT,
    reasoning TEXT,                        -- optional, agent-reported
    confidence REAL,                       -- optional, agent-reported
    model TEXT,                            -- optional, agent-reported
    strategy TEXT,                         -- optional, agent-reported
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS bridge_transfers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    amount_usdc REAL NOT NULL,
    burn_tx_hash TEXT,
    status TEXT DEFAULT 'pending',         -- pending -> attested -> minted -> failed
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS wallet_nonces (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT NOT NULL,
    wallet_address TEXT NOT NULL,
    nonce_hash TEXT NOT NULL UNIQUE,
    expires_at INTEGER NOT NULL,
    used_at INTEGER,
    created_at INTEGER NOT NULL
);
"""

# Your DB is already deployed on Render without these columns, so
# CREATE TABLE IF NOT EXISTS alone won't add them to the existing
# table. This adds them if missing, harmlessly no-ops if they're
# already there.
MIGRATIONS = [
    "ALTER TABLE users ADD COLUMN api_key_hash TEXT",
    "ALTER TABLE users ADD COLUMN permissions_confirmed INTEGER DEFAULT 0",
    "ALTER TABLE users ADD COLUMN last_seen TEXT",
    "ALTER TABLE trades ADD COLUMN reasoning TEXT",
    "ALTER TABLE trades ADD COLUMN confidence REAL",
    "ALTER TABLE trades ADD COLUMN model TEXT",
    "ALTER TABLE trades ADD COLUMN strategy TEXT",
    "ALTER TABLE users ADD COLUMN google_id TEXT",
    "ALTER TABLE users ADD COLUMN email TEXT",
    "ALTER TABLE users ADD COLUMN name TEXT",
    "ALTER TABLE users ADD COLUMN picture TEXT",
    "ALTER TABLE users ADD COLUMN x_id TEXT",
]


def init_db():
    with get_conn() as conn:
        conn.executescript(SCHEMA)
        for stmt in MIGRATIONS:
            try:
                conn.execute(stmt)
            except sqlite3.OperationalError as e:
                if "duplicate column name" in str(e):
                    pass
                else:
                    raise


@contextmanager
def get_conn():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()
